export const fullScreenStyles = {
    container: {
        width: '100vw',
        height: '100vh',
        margin: 0,
        padding: '20px',
        background: 'linear-gradient(135deg, #ff8c42 0%, #ff6b35 100%)',
        display: 'flex',
        flexDirection: 'column',
        alignItems: 'center',
        justifyContent: 'center',
        fontFamily: '"Segoe UI", Tahoma, Geneva, Verdana, sans-serif',
        boxSizing: 'border-box',
        overflow: 'auto',
    },
    header: {
        fontSize: 'clamp(2rem, 5vw, 4rem)',
        color: '#fff',
        marginBottom: '20px',
        textShadow: '2px 2px 4px rgba(0,0,0,0.4)',
        textAlign: 'center',
        fontWeight: 'bold',
    },
    form: {
        background: '#fff',
        padding: 'clamp(20px, 4vw, 40px)',
        borderRadius: '20px',
        boxShadow: '0 20px 40px rgba(0,0,0,0.2)',
        width: '90%',
        maxWidth: '600px',
        minWidth: '280px',
        textAlign: 'center',
        boxSizing: 'border-box',
    },
    input: {
        width: '100%',
        padding: 'clamp(12px, 2vw, 15px)',
        marginBottom: '15px',
        border: '2px solid #ffd7c4',
        borderRadius: '10px',
        fontSize: 'clamp(14px, 2.5vw, 18px)',
        outline: 'none',
        boxSizing: 'border-box',
        transition: 'border-color 0.3s ease',
    },
    button: {
        width: '100%',
        padding: 'clamp(12px, 2vw, 15px)',
        marginBottom: '15px',
        backgroundColor: '#ff6b35',
        color: 'white',
        border: 'none',
        borderRadius: '10px',
        fontSize: 'clamp(14px, 2.5vw, 18px)',
        fontWeight: '600',
        cursor: 'pointer',
        transition: 'all 0.3s ease',
        boxSizing: 'border-box',
    },
    buttonSecondary: {
        backgroundColor: '#fff',
        color: '#ff6b35',
        border: '2px solid #ff6b35',
    },
    participantList: {
        marginTop: '20px',
        textAlign: 'left',
        listStyle: 'none',
        padding: 0,
    },
    participantItem: {
        background: '#fff5f2',
        padding: '10px 15px',
        margin: '5px 0',
        borderRadius: '8px',
        border: '1px solid #ffd7c4',
        color: '#ff6b35',
        fontWeight: '500',
    },
    voteContainer: {
        marginTop: '30px',
        display: 'flex',
        flexWrap: 'wrap',
        justifyContent: 'center',
        gap: '10px',
    },
    voteButton: {
        width: 'clamp(60px, 15vw, 80px)',
        height: 'clamp(60px, 15vw, 80px)',
        fontSize: 'clamp(16px, 3vw, 18px)',
        fontWeight: 'bold',
        borderRadius: '12px',
        border: '2px solid #ffd7c4',
        background: 'white',
        color: '#ff6b35',
        cursor: 'pointer',
        transition: 'all 0.3s ease',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        margin: '5px',
    },
    voteButtonSelected: {
        backgroundColor: '#ff9800',
        color: 'white',
        borderColor: '#ff9800',
    },
    voteButtonDisabled: {
        backgroundColor: '#f5f5f5',
        color: '#ccc',
        cursor: 'not-allowed',
    },
    messageBox: {
        background: '#fff5f2',
        padding: 'clamp(15px, 3vw, 20px)',
        borderRadius: '15px',
        border: '2px solid #ffd7c4',
        marginTop: '20px',
        textAlign: 'center',
        color: '#ff6b35',
        fontWeight: 'bold',
    },
    resultsList: {
        listStyle: 'none',
        padding: 0,
        margin: '15px 0',
    },
    resultItem: {
        display: 'flex',
        justifyContent: 'space-between',
        padding: '8px 0',
        borderBottom: '1px solid #ffd7c4',
        color: '#ff6b35',
    },
    roomInfo: {
        fontSize: 'clamp(1.2rem, 3vw, 1.8rem)',
        color: '#ffffff',
        marginBottom: '15px',
        fontWeight: '600',
    },
    subtitle: {
        fontSize: 'clamp(1rem, 2.5vw, 1.3rem)',
        color: '#ff6b35',
        marginBottom: '10px',
        fontWeight: '500',
    }
};

// Dark theme styles
export const darkTheme = {
    container: {
        width: '100vw',
        height: '100vh',
        margin: 0,
        padding: 0,
        background: '#1a1a1a',
        fontFamily: '"Segoe UI", Tahoma, Geneva, Verdana, sans-serif',
        display: 'flex',
        overflow: 'hidden',
    },
    sidebar: {
        width: '300px',
        background: '#2d2d2d',
        color: '#e0e0e0',
        display: 'flex',
        flexDirection: 'column',
        boxShadow: '2px 0 10px rgba(0,0,0,0.3)',
        zIndex: 1000,
    },
    sidebarHeader: {
        padding: '20px',
        borderBottom: '1px solid #404040',
        background: '#ff6b35',
        textAlign: 'center',
    },
    sidebarTitle: {
        fontSize: '18px',
        fontWeight: 'bold',
        margin: 0,
        color: '#ffffff',
        textTransform: 'uppercase',
        letterSpacing: '1px',
    },
    sidebarContent: {
        flex: 1,
        padding: '20px',
        overflowY: 'auto',
    },
    mainContent: {
        flex: 1,
        display: 'flex',
        flexDirection: 'column',
        background: '#2a2a2a',
    },
    header: {
        background: '#2a2a2a',
        borderBottom: '1px solid #404040',
        padding: '15px 30px',
        display: 'flex',
        justifyContent: 'space-between',
        alignItems: 'center',
        boxShadow: '0 2px 4px rgba(0,0,0,0.3)',
    },
    headerTitle: {
        fontSize: '24px',
        fontWeight: '600',
        color: '#ff6b35',
        margin: 0,
    },
    headerActions: {
        display: 'flex',
        gap: '10px',
    },
    content: {
        flex: 1,
        padding: '30px',
        overflowY: 'auto',
        background: '#1a1a1a',
    },
    card: {
        background: '#2d2d2d',
        borderRadius: '8px',
        boxShadow: '0 2px 8px rgba(0,0,0,0.3)',
        padding: '25px',
        marginBottom: '20px',
        border: '1px solid #404040',
    },
    button: {
        padding: '10px 20px',
        border: 'none',
        borderRadius: '6px',
        fontSize: '14px',
        fontWeight: '500',
        cursor: 'pointer',
        transition: 'all 0.2s ease',
        display: 'inline-flex',
        alignItems: 'center',
        gap: '8px',
    },
    buttonPrimary: {
        backgroundColor: '#ff6b35',
        color: 'white',
    },
    buttonSecondary: {
        backgroundColor: '#5a6c7d',
        color: 'white',
    },
    buttonSuccess: {
        backgroundColor: '#27ae60',
        color: 'white',
    },
    buttonDanger: {
        backgroundColor: '#e74c3c',
        color: 'white',
    },
    buttonSmall: {
        padding: '6px 12px',
        fontSize: '12px',
    },
    input: {
        width: '100%',
        padding: '12px',
        border: '1px solid #404040',
        borderRadius: '6px',
        fontSize: '14px',
        outline: 'none',
        transition: 'border-color 0.2s ease',
        boxSizing: 'border-box',
        background: '#2d2d2d',
        color: '#e0e0e0',
    },
    inputFocus: {
        borderColor: '#ff6b35',
    },
    roomItem: {
        background: '#404040',
        padding: '15px',
        marginBottom: '10px',
        borderRadius: '6px',
        cursor: 'pointer',
        transition: 'all 0.2s ease',
        border: '1px solid transparent',
    },
    roomItemHover: {
        background: '#ff6b35',
        transform: 'translateY(-1px)',
    },
    roomItemActive: {
        background: '#ff6b35',
        borderColor: '#e55a2b',
    },
    roomName: {
        fontSize: '16px',
        fontWeight: '600',
        marginBottom: '5px',
        color: '#ecf0f1',
    },
    roomInfo: {
        fontSize: '12px',
        color: '#ffffff',
        display: 'flex',
        justifyContent: 'space-between',
        alignItems: 'center',
    },
    roomBadge: {
        background: '#ff6b35',
        color: 'white',
        padding: '2px 8px',
        borderRadius: '10px',
        fontSize: '11px',
        fontWeight: 'bold',
    },
    voteGrid: {
        display: 'grid',
        gridTemplateColumns: 'repeat(auto-fit, minmax(70px, 1fr))',
        gap: '15px',
        margin: '20px 0',
    },
    voteButton: {
        width: '70px',
        height: '70px',
        fontSize: '18px',
        fontWeight: 'bold',
        borderRadius: '8px',
        border: '2px solid #404040',
        background: '#2d2d2d',
        color: '#e0e0e0',
        cursor: 'pointer',
        transition: 'all 0.2s ease',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
    },
    voteButtonHover: {
        borderColor: '#ff6b35',
        transform: 'scale(1.05)',
    },
    voteButtonSelected: {
        backgroundColor: '#ff6b35',
        color: 'white',
        borderColor: '#ff6b35',
    },
    voteButtonDisabled: {
        backgroundColor: '#404040',
        color: '#666',
        cursor: 'not-allowed',
        borderColor: '#404040',
    },
    participantList: {
        display: 'grid',
        gridTemplateColumns: 'repeat(auto-fill, minmax(200px, 1fr))',
        gap: '10px',
        margin: '15px 0',
    },
    participantItem: {
        background: '#404040',
        padding: '12px',
        borderRadius: '6px',
        border: '1px solid #505050',
        color: '#e0e0e0',
        fontWeight: '500',
    },
    statsGrid: {
        display: 'grid',
        gridTemplateColumns: 'repeat(auto-fit, minmax(120px, 1fr))',
        gap: '15px',
        margin: '20px 0',
    },
    statCard: {
        background: '#404040',
        padding: '20px',
        borderRadius: '8px',
        textAlign: 'center',
        border: '1px solid #505050',
    },
    statValue: {
        fontSize: '28px',
        fontWeight: 'bold',
        color: '#ff6b35',
        marginBottom: '5px',
    },
    statLabel: {
        fontSize: '12px',
        color: '#bdc3c7',
        textTransform: 'uppercase',
        letterSpacing: '0.5px',
    },
    resultsList: {
        background: '#404040',
        borderRadius: '8px',
        padding: '20px',
        margin: '20px 0',
        border: '1px solid #505050',
    },
    resultItem: {
        display: 'flex',
        justifyContent: 'space-between',
        padding: '10px 0',
        borderBottom: '1px solid #505050',
        color: '#e0e0e0',
    },
    resultItemLast: {
        borderBottom: 'none',
    },
    messageBox: {
        background: '#404040',
        border: '1px solid #ff6b35',
        borderRadius: '6px',
        padding: '15px',
        margin: '15px 0',
        color: '#ff6b35',
        fontWeight: '500',
    },
    emptyState: {
        textAlign: 'center',
        padding: '60px 20px',
        color: '#bdc3c7',
    },
    emptyStateIcon: {
        fontSize: '48px',
        marginBottom: '20px',
        opacity: 0.5,
    },
    sectionTitle: {
        fontSize: '18px',
        fontWeight: '600',
        color: '#ff6b35',
        marginBottom: '15px',
        paddingBottom: '10px',
        borderBottom: '2px solid #404040',
    },
    createRoomForm: {
        background: '#404040',
        padding: '20px',
        borderRadius: '8px',
        marginBottom: '20px',
    },
    formTitle: {
        fontSize: '16px',
        fontWeight: '600',
        color: '#ecf0f1',
        marginBottom: '15px',
    },
    formGroup: {
        marginBottom: '15px',
    },
    formLabel: {
        display: 'block',
        fontSize: '12px',
        color: '#bdc3c7',
        marginBottom: '5px',
        textTransform: 'uppercase',
        letterSpacing: '0.5px',
    },
    sidebarInput: {
        width: '100%',
        padding: '10px',
        border: '1px solid #505050',
        borderRadius: '4px',
        fontSize: '14px',
        background: '#2d2d2d',
        color: '#e0e0e0',
        outline: 'none',
        boxSizing: 'border-box',
    },
    sidebarInputFocus: {
        borderColor: '#ff6b35',
    },
    logo: {
        width: '120px',
        height: '50px',
        marginRight: '15px',
        background: 'white',
        borderRadius: '8px',
        display: 'flex',
        flexDirection: 'column',
        alignItems: 'center',
        justifyContent: 'center',
        color: '#ff6b35',
        fontWeight: 'bold',
        fontSize: '18px',
        boxShadow: '0 4px 12px rgba(0, 0, 0, 0.1)',
        border: '2px solid #ff6b35',
        transition: 'all 0.3s ease',
        textTransform: 'uppercase',
        letterSpacing: '1px',
        position: 'relative',
        overflow: 'hidden',
    },
    themeToggle: {
        padding: '8px 12px',
        border: '1px solid #404040',
        borderRadius: '6px',
        background: '#2d2d2d',
        color: '#e0e0e0',
        cursor: 'pointer',
        transition: 'all 0.2s ease',
        display: 'inline-flex',
        alignItems: 'center',
        gap: '6px',
        fontSize: '12px',
    },
    themeToggleHover: {
        background: '#404040',
        borderColor: '#ff6b35',
    },
};

export const desktopStyles = {
    container: {
        width: '100vw',
        height: '100vh',
        margin: 0,
        padding: 0,
        background: '#fafafa',
        fontFamily: '"Segoe UI", Tahoma, Geneva, Verdana, sans-serif',
        display: 'flex',
        overflow: 'hidden',
    },
    sidebar: {
        width: '300px',
        background: '#2c2c2c',
        color: 'white',
        display: 'flex',
        flexDirection: 'column',
        boxShadow: '2px 0 10px rgba(0,0,0,0.1)',
        zIndex: 1000,
    },
    sidebarHeader: {
        padding: '20px',
        borderBottom: '1px solid #404040',
        background: '#ff6b35',
        textAlign: 'center',
    },
    sidebarTitle: {
        fontSize: '18px',
        fontWeight: 'bold',
        margin: 0,
        color: '#ffffff',
        textTransform: 'uppercase',
        letterSpacing: '1px',
    },
    sidebarContent: {
        flex: 1,
        padding: '20px',
        overflowY: 'auto',
    },
    mainContent: {
        flex: 1,
        display: 'flex',
        flexDirection: 'column',
        background: '#ffffff',
    },
    header: {
        background: '#ffffff',
        borderBottom: '1px solid #e0e0e0',
        padding: '15px 30px',
        display: 'flex',
        justifyContent: 'space-between',
        alignItems: 'center',
        boxShadow: '0 2px 4px rgba(0,0,0,0.1)',
    },
    headerTitle: {
        fontSize: '24px',
        fontWeight: '600',
        color: '#ff6b35',
        margin: 0,
    },
    headerActions: {
        display: 'flex',
        gap: '10px',
    },
    content: {
        flex: 1,
        padding: '30px',
        overflowY: 'auto',
        background: '#fafafa',
    },
    card: {
        background: 'white',
        borderRadius: '8px',
        boxShadow: '0 2px 8px rgba(0,0,0,0.1)',
        padding: '25px',
        marginBottom: '20px',
        border: '1px solid #f0f0f0',
    },
    button: {
        padding: '10px 20px',
        border: 'none',
        borderRadius: '6px',
        fontSize: '14px',
        fontWeight: '500',
        cursor: 'pointer',
        transition: 'all 0.2s ease',
        display: 'inline-flex',
        alignItems: 'center',
        gap: '8px',
    },
    buttonPrimary: {
        backgroundColor: '#ff6b35',
        color: 'white',
    },
    buttonSecondary: {
        backgroundColor: '#95a5a6',
        color: 'white',
    },
    buttonSuccess: {
        backgroundColor: '#27ae60',
        color: 'white',
    },
    buttonDanger: {
        backgroundColor: '#e74c3c',
        color: 'white',
    },
    buttonSmall: {
        padding: '6px 12px',
        fontSize: '12px',
    },
    input: {
        width: '100%',
        padding: '12px',
        border: '1px solid #ddd',
        borderRadius: '6px',
        fontSize: '14px',
        outline: 'none',
        transition: 'border-color 0.2s ease',
        boxSizing: 'border-box',
    },
    inputFocus: {
        borderColor: '#ff6b35',
    },
    roomItem: {
        background: '#404040',
        padding: '15px',
        marginBottom: '10px',
        borderRadius: '6px',
        cursor: 'pointer',
        transition: 'all 0.2s ease',
        border: '1px solid transparent',
    },
    roomItemHover: {
        background: '#ff6b35',
        transform: 'translateY(-1px)',
    },
    roomItemActive: {
        background: '#ff6b35',
        borderColor: '#e55a2b',
    },
    roomName: {
        fontSize: '16px',
        fontWeight: '600',
        marginBottom: '5px',
        color: '#ecf0f1',
    },
    roomInfo: {
        fontSize: '12px',
        color: '#ffffff',
        display: 'flex',
        justifyContent: 'space-between',
        alignItems: 'center',
    },
    roomBadge: {
        background: '#ff6b35',
        color: 'white',
        padding: '2px 8px',
        borderRadius: '10px',
        fontSize: '11px',
        fontWeight: 'bold',
    },
    voteGrid: {
        display: 'grid',
        gridTemplateColumns: 'repeat(auto-fit, minmax(70px, 1fr))',
        gap: '15px',
        margin: '20px 0',
    },
    voteButton: {
        width: '70px',
        height: '70px',
        fontSize: '18px',
        fontWeight: 'bold',
        borderRadius: '8px',
        border: '2px solid #ddd',
        background: 'white',
        color: '#2c3e50',
        cursor: 'pointer',
        transition: 'all 0.2s ease',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
    },
    voteButtonHover: {
        borderColor: '#ff6b35',
        transform: 'scale(1.05)',
    },
    voteButtonSelected: {
        backgroundColor: '#ff6b35',
        color: 'white',
        borderColor: '#ff6b35',
    },
    voteButtonDisabled: {
        backgroundColor: '#f5f5f5',
        color: '#ccc',
        cursor: 'not-allowed',
    },
    participantList: {
        display: 'grid',
        gridTemplateColumns: 'repeat(auto-fill, minmax(200px, 1fr))',
        gap: '10px',
        margin: '15px 0',
    },
    participantItem: {
        background: '#fff8f5',
        padding: '12px',
        borderRadius: '6px',
        border: '1px solid #ffe8e0',
        color: '#ff6b35',
        fontWeight: '500',
    },
    statsGrid: {
        display: 'grid',
        gridTemplateColumns: 'repeat(auto-fit, minmax(120px, 1fr))',
        gap: '15px',
        margin: '20px 0',
    },
    statCard: {
        background: '#fff8f5',
        padding: '20px',
        borderRadius: '8px',
        textAlign: 'center',
        border: '1px solid #ffe8e0',
    },
    statValue: {
        fontSize: '28px',
        fontWeight: 'bold',
        color: '#ff6b35',
        marginBottom: '5px',
    },
    statLabel: {
        fontSize: '12px',
        color: '#e67e22',
        textTransform: 'uppercase',
        letterSpacing: '0.5px',
    },
    resultsList: {
        background: '#fff8f5',
        borderRadius: '8px',
        padding: '20px',
        margin: '20px 0',
        border: '1px solid #ffe8e0',
    },
    resultItem: {
        display: 'flex',
        justifyContent: 'space-between',
        padding: '10px 0',
        borderBottom: '1px solid #ffe8e0',
        color: '#ff6b35',
    },
    resultItemLast: {
        borderBottom: 'none',
    },
    messageBox: {
        background: '#fff8f5',
        border: '1px solid #ff6b35',
        borderRadius: '6px',
        padding: '15px',
        margin: '15px 0',
        color: '#e55a2b',
        fontWeight: '500',
    },
    emptyState: {
        textAlign: 'center',
        padding: '60px 20px',
        color: '#666',
    },
    emptyStateIcon: {
        fontSize: '48px',
        marginBottom: '20px',
        opacity: 0.5,
    },
    sectionTitle: {
        fontSize: '18px',
        fontWeight: '600',
        color: '#ff6b35',
        marginBottom: '15px',
        paddingBottom: '10px',
        borderBottom: '2px solid #ffe8e0',
    },
    createRoomForm: {
        background: '#404040',
        padding: '20px',
        borderRadius: '8px',
        marginBottom: '20px',
    },
    formTitle: {
        fontSize: '16px',
        fontWeight: '600',
        color: '#ecf0f1',
        marginBottom: '15px',
    },
    formGroup: {
        marginBottom: '15px',
    },
    formLabel: {
        display: 'block',
        fontSize: '12px',
        color: '#bdc3c7',
        marginBottom: '5px',
        textTransform: 'uppercase',
        letterSpacing: '0.5px',
    },
    sidebarInput: {
        width: '100%',
        padding: '10px',
        border: '1px solid #4a5f7a',
        borderRadius: '4px',
        fontSize: '14px',
        background: '#2c2c2c',
        color: '#ecf0f1',
        outline: 'none',
        boxSizing: 'border-box',
    },
    sidebarInputFocus: {
        borderColor: '#ff6b35',
    },
    logo: {
        width: '120px',
        height: '50px',
        marginRight: '15px',
        background: 'white',
        borderRadius: '8px',
        display: 'flex',
        flexDirection: 'column',
        alignItems: 'center',
        justifyContent: 'center',
        color: '#ff6b35',
        fontWeight: 'bold',
        fontSize: '18px',
        boxShadow: '0 4px 12px rgba(0, 0, 0, 0.1)',
        border: '2px solid #ff6b35',
        transition: 'all 0.3s ease',
        textTransform: 'uppercase',
        letterSpacing: '1px',
        position: 'relative',
        overflow: 'hidden',
    },
    themeToggle: {
        padding: '8px 12px',
        border: '1px solid #ddd',
        borderRadius: '6px',
        background: 'white',
        color: '#666',
        cursor: 'pointer',
        transition: 'all 0.2s ease',
        display: 'inline-flex',
        alignItems: 'center',
        gap: '6px',
        fontSize: '12px',
    },
    themeToggleHover: {
        background: '#f5f5f5',
        borderColor: '#ff6b35',
    },
};
